<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fxml</string>
	</array>
	<key>name</key>
	<string>FXML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.tag.fxml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import.fxml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.import.fxml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.tag.fxml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>import statements</string>
			<key>match</key>
			<string>(&lt;\?)\s*(import)\s+([^ ;$]+;?)(\?&gt;)</string>
			<key>name</key>
			<string>meta.import.fxml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;\?.*\?&gt;</string>
			<key>name</key>
			<string>meta.tag.preprocessor.fxml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[A-Z]\w*</string>
			<key>name</key>
			<string>entity.name.type.class.fxml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;[!%]--</string>
			<key>end</key>
			<string>--?&gt;</string>
			<key>name</key>
			<string>punctuation.definition.comment.fxml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"([^\"
]|\.)*"</string>
			<key>name</key>
			<string>string.quoted.double.fxml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>tag</string>
			<key>match</key>
			<string>&lt;/</string>
			<key>name</key>
			<string>meta.tag.fxml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>tag</string>
			<key>match</key>
			<string>&lt;</string>
			<key>name</key>
			<string>meta.tag.fxml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>tag</string>
			<key>match</key>
			<string>&gt;</string>
			<key>name</key>
			<string>meta.tag.fxml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>tag</string>
			<key>match</key>
			<string>/&gt;</string>
			<key>name</key>
			<string>meta.tag.fxml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+=</string>
			<key>name</key>
			<string>variable.assignment.fxml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w*</string>
			<key>name</key>
			<string>entity.name.tag.namespace.fxml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fxml</string>
	<key>uuid</key>
	<string>f412ce83-ba1f-4730-a5a4-8f5e73115777</string>
</dict>
</plist>
